# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # @see http://symfony.com/doc/current/bundles/LiipImagineBundle/filters.html
        cache: ~
        default:
            quality: 100
            filters:
                auto_rotate: ~
                relative_resize: { scale: 1 }
        app_original: ~
        app_backend_book_cover_thumbnail:
            filters:
                scale:
                    dim: [ 120, 90 ]
        app_backend_catalogue_cover_thumbnail:
            filters:
                scale:
                    dim: [ 120, 90 ]