imports:
    - { resource: '@SyliusUiBundle/Resources/config/app/config.yml' }

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/backend/manifest.json'
        packages:
            backend:
                json_manifest_path: '%kernel.project_dir%/public/assets/backend/manifest.json'

sylius_ui:
    events:
        sylius.admin.layout.topbar_left:
            blocks:
                sidebar_toggle:
                    template: "backend/layout/_sidebar_toggle.html.twig"
                    priority: 30
                search:
                    template: "backend/layout/_search.html.twig"
                    priority: 10

        sylius.admin.layout.topbar_right:
            blocks:
                security:
                    template: "backend/layout/_security.html.twig"
                    priority: 10
        app.frontend.homepage.content:
            blocks:
                articles:
                    template: "frontend/homepage/content/_articles.html.twig"
                    priority: 10

sonata_block:
    blocks:
        sonata.block.service.template:
            settings:
                customer: ~
                form: ~
                resource: ~
                resources: ~

twig:
    globals:
        app_name_meta:
            version: !php/const App\Kernel::VERSION

sylius_grid:
    templates:
        action:
#            --transaction
            vehicle_state: "backend/vehicle/action/applyTransition.html.twig"
            vehicle_transitions: "backend/grid/action/manageTransitions.html.twig"
            task_status_transitions: "backend/grid/action/manageTransitions.html.twig"
            frontend_task_status_transitions: "frontend/grid/action/manageTransitions.html.twig"
#            --modify frontend action
            update_organisation: "frontend/organisation/action/update.html.twig"
            delete_organisation: "frontend/organisation/action/delete.html.twig"
            delete_task: "frontend/task/action/delete.html.twig"
            update_task: "frontend/task/action/update.html.twig"
#            --links
            show_members: "backend/organisation/action/showMembers.html.twig"
            show_projects: "backend/organisation/action/showProjects.html.twig"
            show_tasks: "backend/project/action/showTasks.html.twig"
#            --action
            create: "common/grid/action/create.html.twig"
            delete: "common/grid/action/delete.html.twig"
            show: "common/grid/action/show.html.twig"
            update: "common/grid/action/update.html.twig"