vich_uploader:
    db_driver: orm

    mappings:
        book_cover:
            uri_prefix: /media/covers
            upload_destination: '%kernel.project_dir%/public/media/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
