framework:
    workflows:
        app_vehicle:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Vehicle\Vehicle
            initial_marking: new
            places:
                - new
                - used
                - salvage
                - totaled
            transitions:
                buy:
                    from: [new, used]
                    to: used
                crash:
                    from: [new, used, salvage]
                    to: totaled
                repair:
                    from: totaled
                    to: salvage

        app_task:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'stateAsString'
            supports:
                - App\Entity\Task\Task
            initial_marking: new
            places:
                - new
                - pending_review
                - awaiting_changes
                - accepted
                - rejected
            transitions:
                create:
                    from: [ new ]
                    to: pending_review
                ask_for_changes:
                    from: [ pending_review, accepted ]
                    to: awaiting_changes
                submit_changes:
                    from: [ awaiting_changes ]
                    to: pending_review
                approve:
                    from: [ pending_review, rejected ]
                    to: accepted

        app_organisation_membership:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'stateAsString'
            supports:
                - App\Entity\Organisation\OrganisationMembership
            initial_marking: new
            places:
                - new
                - pending
                - accepted
                - denied
                - deleted
            transitions:
                request_verification:
                    from: new
                    to: pending
                accept_membership:
                    from: pending
                    to: accepted
                deny_membership:
                    from: pending
                    to: denied
                delete_membership:
                    from: [ new, pending, accepted, denied ]
                    to: deleted