version: "3.8"
services:
  mailhog:
    # do not use in production!
    image: mailhog/mailhog:latest
    environment:
      MH_STORAGE: "maildir"
    # volumes:
    #   - ./docker/mailhog/maildir:/maildir:rw,delegated
    ports:
      - "1025:1025"
      - "8025:8025"
