App\Entity\Book\Category:
    attributes:
        code:
            groups: [ sylius,Autocomplete ]
        name:
            groups: [ sylius,Autocomplete ]
        id:
            groups: [ sylius ]