app_frontend_ajax:
  resource: "ajax.yaml"
  prefix: /ajax

app_account:
  resource: "account.yaml"
  prefix: "account"

sylius_security:
  resource: "security.yaml"

app_article:
  resource: "article.yaml"

app_book:
  resource: "book.yaml"

app_frontend_partial:
  resource: "partial.yaml"
  prefix: "/_partial"
