app_frontend_book_show:
    path: /book/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.book::showAction
        _sylius:
            redirect: app_frontend_book_show
            template: "frontend/book/show.html.twig"
            repository:
                method: find
                arguments:
                    - $id
