app_frontend_project_index:
    path: /
    defaults:
        _controller: app.controller.project::indexAction
        _sylius:
            section: frontend
            template: frontend/crud/index.html.twig
            grid: app_frontend_project

app_frontend_project_create:
    path: /new
    methods: [ GET, POST ]
    defaults:
        _controller: app.controller.project::createAction
        _sylius:
            section: frontend
            template: frontend/crud/create.html.twig
            redirect:
                route: app_frontend_project_index
            factory:
                method: createNewWithOrganisation
                arguments:
                    - expr:service('App\\\Context\\\OrganisationContext').getOrganisation()

app_frontend_project_update:
    path: /{id}/edit
    methods: [ GET, PUT ]
    defaults:
        _controller: app.controller.project::updateAction
        _sylius:
            section: frontend
            template: frontend/crud/update.html.twig
            redirect:
                route: app_frontend_project_index

app_frontend_project_delete:
    path: /{id}
    methods: [ DELETE ]
    defaults:
        _controller: app.controller.project::deleteAction
        _sylius:
            section: frontend
            redirect: referer
            vars:
                route:
                    parameters:
                        organisationId: $organisationId