sylius_backend_article:
    resource: |
        section: backend
        alias: app.article
        templates: 'backend/crud'
        except: ['show']
        grid: app_backend_article
        redirect: index
        vars:
            all:
                subheader: app.ui.manage_your_articles
                templates:
                    form: backend/article/_form.html.twig
            index:
                icon: users
    type: sylius.resource


app_backend_article_add:
    path: /articles/add
    defaults:
        _controller: app.controller.article::addAction
#        _sylius :
#            template: backend/article/testAdd.html.twig

app_backend_article_show:
    path: /articles/{id}
    defaults:
        _controller: app.controller.article::showAction
        _sylius:
            section: backend
            template: backend/article/show.html.twig
            permission: true

