sylius_backend_article:
    resource: |
        section: backend
        alias: app.book
        templates: 'backend/crud'
        except: ['show']
        grid: app_backend_book
        redirect: index
        vars:
            all:
                subheader: app.ui.manage_your_books
                templates:
                    form: backend/book/_form.html.twig
            index:
                icon: book
    type: sylius.resource

app_backend_book_show:
    path: /book/{id}
    defaults:
        _controller: app.controller.book::showAction
        _sylius:
            section: backend
            template: backend/book/show.html.twig
            permission: true

