app_backend_organisation_membership_index:
    path: /
    defaults:
        _controller: app.controller.organisation_membership::indexAction
        _sylius:
            section: backend
            template: backend/crud/index.html.twig
            grid: app_backend_organisation_membership
            permission: true
            vars:
                breadcrumb: 'app.ui.organisations'
                route:
                    parameters:
                        organisationId: $organisationId
                templates:
                    breadcrumb: backend/organisation_membership/index/_breadcrumb.html.twig

app_backend_organisation_membership_create:
    path: /new
    methods: [ GET, POST ]
    defaults:
        _controller: app.controller.organisation_membership::createAction
        _sylius:
            section: backend
            template: backend/crud/create.html.twig
            redirect:
                route: app_backend_organisation_membership_index
                parameters: { organisationId: $organisationId }
            vars:
                route:
                    parameters:
                        organisationId: $organisationId
            factory:
                method: createNewWithOrganisation
                arguments:
                    - expr:service('app.repository.organisation').find($organisationId)

app_backend_organisation_membership_update:
    path: /{id}/edit
    methods: [ GET, PUT ]
    defaults:
        _controller: app.controller.organisation_membership::updateAction
        _sylius:
            section: backend
            template: backend/crud/update.html.twig

            redirect:
                route: app_backend_organisation_membership_index
                parameters: { organisationId: $organisationId }
            vars:
                breadcrumb: 'app.ui.organisations'
                templates:
                    breadcrumb: backend/organisation_membership/update/_breadcrumb.html.twig
                route:
                    parameters:
                        organisationId: $organisationId
                        id: $id

app_backend_organisation_membership_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: app.controller.organisation_membership::deleteAction
        _sylius:
            section: backend
            redirect: referer
            permission: true