app_backend_project_index:
    path: /
    defaults:
        _controller: app.controller.project::indexAction
        _sylius:
            section: backend
            template: backend/crud/index.html.twig
            grid: app_backend_project
            vars:
                breadcrumb: 'app.ui.organisations'
                route:
                    parameters:
                        organisationId: $organisationId
                templates:
                    breadcrumb: backend/project/index/_breadcrumb.html.twig

app_backend_project_create:
    path: /new
    methods: [ GET, POST ]
    defaults:
        _controller: app.controller.project::createAction
        _sylius:
            section: backend
            template: backend/crud/create.html.twig
            redirect:
                route: app_backend_project_index
                parameters: { organisationId: $organisationId }
            vars:
                breadcrumb: 'app.ui.organisations'
                route:
                    parameters:
                        organisationId: $organisationId
                templates:
                    breadcrumb: backend/project/index/_breadcrumb.html.twig
            factory:
                method: createNewWithOrganisation
                arguments:
                    - expr:service('app.repository.organisation').find($organisationId)

app_backend_project_update:
    path: /{id}/edit
    methods: [ GET, PUT ]
    defaults:
        _controller: app.controller.project::updateAction
        _sylius:
            section: backend
            template: backend/crud/update.html.twig
            redirect:
                route: app_backend_project_index
                parameters: { organisationId: $organisationId }
            vars:
                breadcrumb: 'app.ui.organisations'
                templates:
                    breadcrumb: backend/project/update/_breadcrumb.html.twig
                route:
                    parameters:
                        organisationId: $organisationId
                        id: $id

app_backend_project_delete:
    path: /{id}
    methods: [ DELETE ]
    defaults:
        _controller: app.controller.project::deleteAction
        _sylius:
            section: backend
            redirect: referer
            vars:
                route:
                    parameters:
                        organisationId: $organisationId