app_backend_task_index:
    path: /
    defaults:
        _controller: app.controller.task::indexAction
        _sylius:
            section: backend
            template: backend/crud/index.html.twig
            grid: app_backend_task
            vars:
                breadcrumb: 'app.ui.projects'
                route:
                    parameters:
                        projectId: $projectId
                templates:
                    breadcrumb: backend/task/index/_breadcrumb.html.twig

app_backend_task_create:
    path: /new
    methods: [ GET, POST ]
    defaults:
        _controller: app.controller.task::createAction
        _sylius:
            section: backend
            template: backend/crud/create.html.twig
            redirect:
                route: app_backend_task_index
                parameters: { projectId: $projectId }
            vars:
                breadcrumb: 'app.ui.projects'
                route:
                    parameters:
                        projectId: $projectId
                templates:
                    breadcrumb: backend/task/index/_breadcrumb.html.twig
            factory:
                method: createNewWithProject
                arguments:
                    - expr:service('app.repository.project').find($projectId)


app_backend_task_update:
    path: /{id}/edit
    methods: [ GET, PUT ]
    defaults:
        _controller: app.controller.task::updateAction
        _sylius:
            section: backend
            template: backend/crud/update.html.twig
            route:
                parameters: { projectId: $projectId }
            redirect:
                route: app_backend_task_index
                parameters: { projectId: $projectId }
            vars:
                breadcrumb: 'app.ui.projects'
                route:
                    parameters:
                        projectId: $projectId
                        id: $id
                templates:
                    breadcrumb: backend/task/update/_breadcrumb.html.twig
#                    form: backend/task/_form.html.twig

app_backend_task_delete:
    path: /{id}
    methods: [ DELETE ]
    defaults:
        _controller: app.controller.task::deleteAction
        _sylius:
            section: backend
            redirect: referer
            vars:
                route:
                    parameters:
                        organisationId: $organisationId

# workflow routes start
app_backend_task_transition_create:
    path: /task/{id}/create
    methods: [PUT]
    defaults:
        _controller: app.controller.task::applyStateMachineTransitionAction
        _sylius:
            redirect:
                route: app_backend_task_index
                parameters: { projectId: $projectId }
            state_machine:
                graph: app_task
                transition: create

app_backend_task_transition_ask_for_changes:
    path: /task/{id}/ask_for_changes
    methods: [PUT]
    defaults:
        _controller: app.controller.task::applyStateMachineTransitionAction
        _sylius:
            redirect:
                route: app_backend_task_index
                parameters: { projectId: $projectId }
            state_machine:
                graph: app_task
                transition: ask_for_changes

app_backend_task_transition_submit_changes:
    path: /task/{id}/submit_changes
    methods: [PUT]
    defaults:
        _controller: app.controller.task::applyStateMachineTransitionAction
        _sylius:
            redirect:
                route: app_backend_task_index
                parameters: { projectId: $projectId }
            state_machine:
                graph: app_task
                transition: submit_changes

app_backend_task_transition_approve:
    path: /task/{id}/approve
    methods: [PUT]
    defaults:
        _controller: app.controller.task::applyStateMachineTransitionAction
        _sylius:
            redirect:
                route: app_backend_task_index
                parameters: { projectId: $projectId }
            state_machine:
                graph: app_task
                transition: approve
# workflow routes end